name: Generate Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the version of Python you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script to Generate Report
        run: |
          python generate_report.py

      - name: Upload Report as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-report
          path: ./report.txt  # Ensure this is the path where your report is generated
